### PR TITLE
Added traceback log before raise ZbxImportError exception; Ensure pyt…

### PR DESCRIPTION
**Pull request by magau**
…hon2 compatibility...

### CODE REVIEW

**Comment by selivan** [comment]
Python2 is not supported since of April 20, 2020 with last release 2.7.18. I don't mind keeping compatibility if someone uses this script on obsolete systems, though.

Just one question:

```
    except: #python2
        with open(template_file, 'r') as f:
            source = f.read()
```

I suppose this code will break templates with non-ASCII item and trigger names on python2. I suggest to change it to something like

```
import io
with io.open(template_file, 'r', encoding='utf8') as f:
```

**Comment by magau** [comment]
Hi Selivan!
About Python2 descontinuation, I totally agree whith you. Unfortunatly, obsolete systems that still using it and can not be updated for reasons that are out of my decision scope, prolifere as rats...

**Comment by magau** [comment]
About your question regarding the ascci encoding. I also agree with you.
Just one more thing, I don't to bother you with my own needs. I propose you merge requests because even after reading your lisence, that I musts say you earned my respect with that,  I feel like this is your project. So, if you just feel like I'm bothering too much I'll do it in my own trunk.
Any way thank you, once again! ;)

**Comment by selivan** [comment]
I am not bothered at all, I really like to see that my work is useful for somebody. That's the reason I share it.

I will accept this PR, but I will add `io.open()` hack for python2 on top of that to to deal with encoding.

Thank you for the contribution!

**Pull request merged**
